
BLENDER="C:\Program Files\Blender Foundation\Blender 4.5\blender.exe"
DIST=../dist

all : \
    $(DIST)/egbdf.pnct \
    $(DIST)/egbdf.scene \

$(DIST)/egbdf.scene : egbdf.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "egbdf.blend:Main" "$(DIST)/egbdf.scene"

$(DIST)/egbdf.pnct : egbdf.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "egbdf.blend:Main" "$(DIST)/egbdf.pnct" 
